#!/bin/bash
UPSTREAM_NET_INTERFACE=wlan0
HOSTED_NET_INTERFACE=wlan1

sudo iptables -t nat -A POSTROUTING -o $UPSTREAM_NET_INTERFACE -j MASQUERADE
sudo iptables -A FORWARD -i $UPSTREAM_NET_INTERFACE -o $HOSTED_NET_INTERFACE -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i $HOSTED_NET_INTERFACE -o $UPSTREAM_NET_INTERFACE -j ACCEPT
